# Generated by Django 3.2 on 2021-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(default='Digita sua anotação!', max_length=200),
        ),
    ]
